# Node-specific configuration
# The keygen, frost_address, and kupo settings are inherited from config.base.yaml
# Only override them here if you need different values from the base config

peers:
  - address: 127.0.0.1:8001
    label: Descriptive label
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAtYoVpsW+gRlzXM9Iu3OBoopNj6y5OB8oeOJIWD10G/U=
      -----END PUBLIC KEY-----
  - address: 127.0.0.1:8002
    label: Who's this
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAg1sXWpm7CUeBGj9pdCgAVjKtJhEwL9s3BH1Ua9y6Nm0=
      -----END PUBLIC KEY-----
