# Node 0 Configuration
# Inherits from config.base.yaml

# List all peer nodes
peers:
  - address: node1:31415
    label: Node 1
    public_key: |
      -----BEGIN PUBLIC KEY-----
      MCowBQYDK2VwAyEAlFpA1u62EKm2Kx26lCGEVaysJxYGeVDSqhjKLonPk/Y=
      -----END PUBLIC KEY-----